-- monadic — shared primitives
--
-- Conventions used across every migration in this project:
--   * Surrogate uuid primary keys, generated by the database.
--   * timestamptz everywhere. No naked `timestamp`.
--   * `updated_at` is maintained by trigger, never by the application.
--   * Vocabularies that are SETTLED use a CHECK constraint.
--     Vocabularies that are UNSETTLED use a lookup table (insert, not migrate)
--     or plain `text` validated in the application layer.
--   * Every table sourced from an external API carries an untouched `raw` jsonb.

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

comment on function public.set_updated_at() is
  'Trigger function. Stamps updated_at on every UPDATE. Attached per-table.';

-- ---------------------------------------------------------------------------
-- ATS sources
-- ---------------------------------------------------------------------------
-- This one IS an enum rather than a lookup table: a source only exists if a
-- puller has been written for it, so adding a value is always accompanied by a
-- code change anyway. Postgres allows `alter type ... add value` cheaply.

create type public.ats_source as enum ('greenhouse', 'ashby', 'lever');
